# Generated by Django 5.2.8 on 2025-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcomment',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
